services:
  api:
    build: .
    depends_on:
      - qdrant_db
    ports:
      - "8000:80"
    
  qdrant_db:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
    volumes:
      - /var/lib/qdrant_data
        
volumes:
  qdrant_data: